name: Simple CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  success-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print success message
        run: |
          echo Workflow ran successfully