name: Simple CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Running tests..."
      - name: Deployment
        uses: actions/checkout@v2
        run: |
          echo "Deploying..."
      - name: Result
        run: |
          echo "Workflow success!"